### ISSUE TITLE
Pins 30 and 31 are backwards

### ISSUE THREAD

**Issue by dcnichols** [algoaccess/pcb-breakout-bmd300#1]
Hi yeokm1,

The BMD-300 package has an error on it where pin30 and pin 31 have their location swapped. You can redownload the fixed eagle library part from the Rigado BMD-300 page, or fixed the package in your library (the symbol and mapping are correct, just the package is wrong). For your breakout board, this means that P0.13 is grounded, and the pin labeled P0.13 : P31 is actually a ground (through the module).

**Comment by yeokm1** [comment]
Thanks for pointing our the error! I have adjusted my board to use the newer library.
